// front/src/components/hero.tsx
import {component$} from '@builder.io/qwik'

interface HeroProps {
  title: string
  image: string
  alt: string
}

export default component$<HeroProps>((props: HeroProps) => {
  return (
    <div id="hero" class="relative rounded text-center">
      <img id="hero-image" class="h-full object-cover w-full" src={`/images/${props.image}-1350.webp`} alt={props.alt} />
      <div id="hero-content" class="text-center text-white w-full">
        <h1 class="m-0">{props.title}</h1>
      </div>
    </div>
  )
})

// sveltekit/src/lib/Hero.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import {host, religion, siteName} from '$lib/store'
	import Breadcrumb from '$lib/Breadcrumb.svelte'

	export let alt: string
  export let image: string
  export let title: string
	export let description: string|null = null
	export let pages: {name: string, url: string}[] | null = null

	$: imageUrl = `/images/${image}`
	$: metaTitle = $siteName === title ? title : `${title} | ${$siteName}`
</script>

<svelte:head>
	<title>{metaTitle}</title>
	<meta name="twitter:title" property="og:title" content={title} />
	<meta name="description" content={description ?? $religion?.description} />
	<meta name="twitter:description" property="og:description" content={description ?? $religion?.description} />
	<meta name="canonical" property="og:url" content={`${$host}${$page.url.pathname}`} />
	<meta name="twitter:image" property="og:image" content={`${$host}${imageUrl}-1350.webp`} />
</svelte:head>

<div id="hero" class="relative text-center">
	<img
		id="hero-image"
		class="block h-full object-cover w-full"
		srcset={`${imageUrl}-400.webp 400w, ${imageUrl}-635.webp 635w, ${imageUrl}-1350.webp 1350w`}
		sizes="(max-width: 500px) 400px, (max-width: 768px) 635px, 1350px"
		src={`${imageUrl}-1350.webp`}
		{alt}
		width="1350"
		height="500"
		decoding="async"
		loading="eager"
		aria-hidden="true"
	/>
	<div id="hero-content" class="absolute bottom-6 left-0 text-white w-full">
		<h1 class="leading-tight m-0 mx-auto">{title}</h1>
	</div>
</div>

{#if Array.isArray(pages)}
	<Breadcrumb {pages}/>
{/if}
